---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
  labels:
    app: hello-world
spec:
  replicas: 10
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      hostNetwork: true
      containers:
      - name: hello-world
        image: suryaobulareddy2932/hello-world
        ports:
        - containerPort: 8100
      restartPolicy: Always
      securityContext:
       fsGroup: 0
       runAsUser: 0
      volumes:
       - name: hello-world
         persistentVolumeClaim:
          claimName: nfs-pvc-jenkins
---        
apiVersion: v1
kind: Service
metadata:
  name: hello-world
spec:
  ports:
    - port: 8100
      targetPort: 8100
      name: "http"
      nodePort: 31000
  type: LoadBalancer
  externalIPs:
    - 164.52.219.186
  selector:
    app: hello-world

