---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
  labels:
    app: hello-world
spec:
  replicas: 5
  selector:
    matchLabels:
      app: hello-world
      tier: backend
      track: stable
  minReadySeconds: 10
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: hello-world
        tier: backend
        track: stable
    spec:
      containers:
      - name: hello-world
        image: suryaobulareddy2932/hello-world:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8100
          name: http
      restartPolicy: Always
---        
apiVersion: v1
kind: Service
metadata:
  name: hello-world
spec:
  ports:
    - port: 8100
      targetPort: 8100
      name: "http"
      nodePort: 31000
#   type: LoadBalancer
  type: NodePort 
#   externalIPs:
#     - 164.52.219.186
#     - 164.52.219.187
  selector:
    app: hello-world

