--- 
apiVersion: apps/v1
kind: Deployment
metadata: 
  labels: 
    app: hello-world
  name: surya-hello-world
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      app: jenkins
  template: 
    metadata: 
      labels: 
        app: jenkins
    spec: 
      containers: 
        - 
          image: suryaobulareddy2932/hello-world
          name: jenkins
          ports: 
            - 
              containerPort: 8100
      hostNetwork: true
      restartPolicy: Always
      securityContext: 
        fsGroup: 0
        runAsUser: 0
      volumes: 
        - 
          name: jenkins
          persistentVolumeClaim: 
            claimName: nfs-pvc-jenkins
