apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-web-app
  labels:
    app: node-web-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-web-app
  template:
    metadata:
      labels:
        app: node-web-app
    spec:
      hostNetwork: true
      containers:
      - name: node-web-app 
        image: suryaobulareddy2932/hello-world 
        ports:
        - name: http-port
          containerPort: 8100
      restartPolicy: Always
      securityContext:
       fsGroup: 0 
       runAsUser: 0
      volumes:
       - name: node-web-app
         persistentVolumeClaim:
          claimName: nfs-pvc-jenkins
